remote_theme: b2a3e8/jekyll-theme-console
listen_for_clients_preferred_style: true
style: light

header_pages:
  - index.md
  - about.md

footer: '<a href="https://github.com/NiumXp">https://github.com/NiumXp</a>'
